export const en = {
  nav: { problem: 'Problem', results: 'Results', methodology: 'Services', cases: 'Success Stories', team: 'Team', blog: 'Blog', cta: 'Book a Call' },
  hero: { tag: 'Specialists in B2B & B2C Fintech Growth', title: 'Your fintech can grow faster, ', titleHighlight: 'without spending more on marketing.', subtitle: 'We help you create a growth engine that lasts over time and reduces your CAC by leveraging the value of trust.', ctaPrimary: 'Start now', ctaSecondary: 'View services', trust: 'Companies validated by trust' },
  problem: { title: 'The traditional model is broken', subtitle: 'In a saturated market, relying 100% on Paid Media is unsustainable.', cards: [ { title: 'Renting Attention', desc: 'If you cut the ad budget, sales die instantly.' }, { title: 'Uncontrollable CAC', desc: 'Cost per click keeps rising. Without owned assets, your profitability erodes.' }, { title: 'Trust Friction', desc: 'The Fintech user is skeptical. You attract traffic, but don\'t convert due to lack of authority.' }, { title: 'Silent Churn', desc: 'You capture registrations, not clients. LTV never covers the acquisition cost.' } ] },
  results: { title: 'Trust Engine Results', subtitle: 'Predictable and scalable growth.', cards: [ { title: '70% Reduction in CAC', desc: 'We replace inflated ad spend with organic trust systems and structured virality.' }, { title: 'Activated Users', desc: 'We leave vanity metrics behind. We attract ideal customers (ICP) ready to use and pay.' }, { title: '24/7 Machine', desc: 'We implement automation and AI so that acquisition works without depending on manual labor.' }, { title: 'Assets that last', desc: 'We build a growth engine that gains traction over time, increasing LTV.' } ] },
  methodology: {
    title: 'The right growth engine.',
    subtitle: 'Scalable infrastructure according to your business stage.',
    stages: [
      { step: 'Stage 1', title: 'SEEKING PMF', tag: '0 → Real Traction', desc: 'We perform **rapid iteration**: channel testing, messaging, and competitor analysis to find your positioning. A value proposition that guides product development.', icon: 'search', guaranteeTitle: 'OBJECTIVE & GUARANTEE', guarantees: [ 'Validation of **Value Proposition** and unique positioning.', 'Generation of the first **paying users**.' ] },
      { step: 'Stage 2', title: 'SCALING', tag: '10K → 500K Users', desc: 'We implement the **Trust Engine**: building trust by positioning the brand in **authoritative media and influencers**. A growth engine that prioritizes real customers.', icon: 'trending-up', guaranteeTitle: 'OBJECTIVE & GUARANTEE', guarantees: [ 'Organic traction and brand recognition via **Referral**.', 'Conversion of **Paying Clients** and high LTV.' ] },
      { step: 'Stage 3', title: 'EXPANSION', tag: 'New Market / Product', desc: '**Go-to-Market** plan to launch new products or start operations in **Spain**. We identify competitive niches to ensure strategic traction.', icon: 'globe', guaranteeTitle: 'OBJECTIVE & GUARANTEE', guarantees: [ 'Initial traction secured in **high-conversion niches**.', 'Rapid penetration with **localized strategy**.' ] }
    ]
  },
  cases: { title: 'Success Stories', subtitle: 'Real audited results.', list: [ { company: 'BNEXT', stat: '500K', label: 'Active users', highlight: 'achieved in 30 months', summary: 'From 0 to 500,000 users in 30 months, without spending millions on advertising.', challenge: 'Scaling the user base in a competitive market without relying exclusively on massive paid media.', solution: 'We built a growth system based on trust and virality.' }, { company: 'BIT2ME', stat: '-70%', label: 'CAC Reduction', highlight: 'implementing Trust Engine', summary: 'We reduced CAC by 70% implementing the Trust Engine.', challenge: 'Acquisition cost skyrocketed due to ad saturation and mistrust in the crypto sector.', solution: 'We optimized data, segmentation and activation to double the value of each client.' }, { company: 'GOCARDLESS', stat: '10K €', label: 'MRR reached', highlight: 'in 6 months from launch', summary: 'Launch from scratch in Spain and Portugal reaching 10k MRR quickly.', challenge: 'Entry into new markets without previous brand presence.', solution: 'Strategy focused on content, alliances and intelligent sales.' } ], btnRead: 'Read full case', btnHide: 'Show less', challengeLabel: 'Challenge', solutionLabel: 'Solution' },
  team: { title: 'Trust is what matters, get to know us', bioAlfonso: 'Growth specialist with more than ten years launching and scaling fintech products.', bioMartin: 'Technical growth specialist with more than ten years creating automation and data systems that scale operations.' },
  blog: { title: 'Blog & Insights', subtitle: 'Strategic resources to scale your fintech.', cta: 'View all articles', readTime: 'min read', admin: 'Admin', empty: 'Coming soon...' },
  footer: { title: 'Scale your Fintech today.', ctaEmail: 'accounts@growth4u.io', ctaCall: 'Book a Call', rights: '© 2025 Growth4U. All rights reserved.', privacy: 'Privacy Policy', terms: 'Cookie Policy' }
};
