export const es = {
  nav: { problem: 'Problema', results: 'Resultados', methodology: 'Servicios', cases: 'Casos de Éxito', team: 'Equipo', blog: 'Blog', cta: 'Agendar Llamada' },
  hero: { tag: 'Especialistas en Growth para Empresas Tech B2B & B2C', title: 'Tu empresa tech puede crecer más rápido, ', titleHighlight: 'sin invertir más en marketing.', subtitle: 'Te ayudamos a crear un motor de crecimiento que perdura en el tiempo y reduce tu CAC apoyándonos en el valor de la confianza.', ctaPrimary: 'Empezar ahora', ctaSecondary: 'Ver servicios', trust: 'Empresas validadas por la confianza' },
  problem: { title: 'El modelo tradicional está roto', subtitle: 'En un mercado saturado, depender 100% de Paid Media es insostenible.', cards: [ { title: 'Alquiler de Atención', desc: 'Si cortas el presupuesto de anuncios, las ventas mueren instantáneamente.' }, { title: 'CAC Incontrolable', desc: 'El coste por clic no para de subir. Sin activos propios, tu rentabilidad se erosiona.' }, { title: 'Fricción de Confianza', desc: 'El usuario tech es escéptico. Atraes tráfico, pero no conviertes por falta de autoridad.' }, { title: 'Churn Silencioso', desc: 'Captas registros, no clientes. El LTV nunca llega a cubrir el coste de adquisición.' } ] },
  results: { title: 'Resultados del Trust Engine', subtitle: 'Crecimiento predecible y escalable.', cards: [ { title: 'Reducción del 70% en CAC', desc: 'Sustituimos el gasto publicitario inflado por sistemas de confianza orgánica y viralidad estructurada.' }, { title: 'Usuarios Activados', desc: 'Dejamos atrás las vanity metrics. Atraemos clientes ideales (ICP) listos para usar y pagar.' }, { title: 'Máquina 24/7', desc: 'Implementamos automatización e IA para que la captación funcione sin depender de trabajo manual.' }, { title: 'Activos que perduran', desc: 'Construimos un motor de crecimiento que gana tracción con el tiempo, aumentando el LTV.' } ] },
  methodology: {
    title: 'El motor de crecimiento adecuado.',
    subtitle: 'Infraestructura escalable según la etapa de tu negocio.',
    stages: [
      { step: 'Etapa 1', title: 'BUSCANDO PMF', tag: '0 → Tracción Real', desc: 'Realizamos **iteración rápida**: testeo de canales, mensajes y análisis de competidores para encontrar tu posicionamiento. Una propuesta de valor que guía el desarrollo del producto.', icon: 'search', guaranteeTitle: 'OBJETIVO & GARANTÍA', guarantees: [ 'Validación de **Propuesta de Valor** y posicionamiento único.', 'Generación de los primeros **usuarios que pagan**.' ] },
      { step: 'Etapa 2', title: 'ESCALANDO', tag: '10K → 500K Users', desc: 'Implementamos el **Trust Engine**: generamos confianza posicionando la marca en **medios de autoridad e influencers**. Un motor de crecimiento que prioriza clientes reales.', icon: 'trending-up', guaranteeTitle: 'OBJETIVO & GARANTÍA', guarantees: [ 'Tracción orgánica y reconocimiento de marca vía **Referral**.', 'Conversión de **Clientes que pagan** y alto LTV.' ] },
      { step: 'Etapa 3', title: 'EXPANSIÓN', tag: 'Nuevo Mercado / Producto', desc: 'Plan de **Go-to-Market** para lanzar nuevos productos o iniciar operaciones en **España**. Identificamos nichos competitivos para asegurar tracción estratégica.', icon: 'globe', guaranteeTitle: 'OBJETIVO & GARANTÍA', guarantees: [ 'Tracción inicial asegurada en **nichos de alta conversión**.', 'Penetración rápida con **estrategia localizada**.' ] }
    ]
  },
  cases: { title: 'Casos de Éxito', subtitle: 'Resultados reales auditados.', list: [ { company: 'BNEXT', stat: '500K', label: 'usuarios en menos de 30 meses', highlight: 'De 0 a 500.000 usuarios con un CAC de €12,50', summary: 'De 0 a 500.000 usuarios construyendo un sistema de confianza delegada con +300 afiliados.', challenge: 'Mercado saturado, Revolut y N26 con ventaja, pereza bancaria española.', solution: 'Trust Engine: nichos desatendidos, incentivo 10€ al instante, +300 afiliados.' }, { company: 'BIT2ME', stat: '-70%', label: 'CAC + x7 usuarios', highlight: 'De 250K€/mes en paid a crecimiento sostenible', summary: 'De quemar 250K€/mes en paid a x7 usuarios y €686K revenue por cohorte mensual.', challenge: 'Bear market, 250K€/mes en paid sin retorno, percepción de "caro" post-FTX.', solution: 'Trust Engine: regulación como fortaleza, confianza delegada, paid como amplificador.' }, { company: 'GOCARDLESS', stat: '10K €', label: 'MRR en 6 meses', highlight: 'Lanzamiento desde cero en España y Portugal', summary: 'Go-to-market en España y Portugal alcanzando 10K MRR en 6 meses desde cero.', challenge: 'Entrada en nuevos mercados sin presencia de marca previa.', solution: 'Contenido, alianzas estratégicas y ventas inteligentes.' } ], btnRead: 'Leer caso completo', btnHide: 'Ver menos', challengeLabel: 'Reto', solutionLabel: 'Solución' },
  team: { title: 'La confianza es lo importante, conócenos', bioAlfonso: 'Especialista en growth con más de diez años lanzando y escalando productos tech.', bioMartin: 'Especialista en growth técnico con más de diez años creando sistemas de automatización y datos que escalan operaciones.' },
  blog: { title: 'Blog & Insights', subtitle: 'Recursos estratégicos para escalar tu empresa tech.', cta: 'Ver todos los artículos', readTime: 'min lectura', admin: 'Admin', empty: 'Próximamente nuevos artículos...' },
  footer: { title: 'Escala tu Empresa Tech hoy.', ctaEmail: 'accounts@growth4u.io', ctaCall: 'Agendar Llamada', rights: '© 2025 Growth4U. Todos los derechos reservados.', privacy: 'Política de Privacidad', terms: 'Política de Cookies' }
};
